# Generated by Django 4.0.6 on 2024-12-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('organizador', models.CharField(max_length=100)),
                ('cupo_maximo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion', models.DurationField()),
                ('nivel_dificultad', models.CharField(choices=[('Facil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('equipo_necesario', models.TextField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Gestiones.evento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividades', to='Gestiones.actividad')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_actividades', to='Gestiones.participante')),
            ],
            options={
                'unique_together': {('participante', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Gestiones.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Gestiones.participante')),
            ],
            options={
                'unique_together': {('participante', 'evento')},
            },
        ),
    ]
